---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.podinfod: semver:~1.8
  name: backend
  namespace: team1
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: podinfod
      containers:
      - image: quay.io/stefanprodan/podinfo:1.8.0
        name: podinfod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.podinfod: semver:~1.7
    fluxcd.io/locked: "true"
    fluxcd.io/locked_user: Nestor Lobo <mlobo@mural.co>
  name: frontend
  namespace: team1
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: podinfod
      containers:
      - image: quay.io/stefanprodan/podinfo:1.7.4
        name: podinfod
